import type { IconType } from "react-icons";

import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineBolt,
  HiOutlineBriefcase,
  HiOutlineCircleStack,
  HiOutlineCloud,
  HiOutlineCommandLine,
  HiOutlineCpuChip,
  HiOutlineCube,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlinePaintBrush,
  HiOutlineRocketLaunch,
  HiOutlineServerStack,
  HiOutlineSparkles,
  HiOutlineWrenchScrewdriver,
} from "react-icons/hi2";

import {
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";

import {
  SiAmazonwebservices,
  SiBootstrap,
  SiCelery,
  SiDjango,
  SiDocker,
  SiFastapi,
  SiFigma,
  SiFirebase,
  SiFlask,
  SiJavascript,
  SiMongodb,
  SiNextdotjs,
  SiPostgresql,
  SiRedis,
  SiRender,
  SiSqlite,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

import {
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaInstagram,
  FaLinkedin,
  FaPinterest,
  FaPython,
  FaReact,
  FaReddit,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  services: HiOutlineBriefcase,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  react: FaReact,
  supabase: SiSupabase,
  firebase: SiFirebase,
  figma: SiFigma,
  python: FaPython,
  django: SiDjango,
  fastapi: SiFastapi,
  flask: SiFlask,
  celery: SiCelery,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  docker: SiDocker,
  aws: SiAmazonwebservices,
  render: SiRender,
  bootstrap: SiBootstrap,
  tailwind: SiTailwindcss,
  ai: HiOutlineSparkles,
  cloud: HiOutlineCloud,
  devops: HiOutlineServerStack,
  terminal: HiOutlineCommandLine,
  database: HiOutlineCircleStack,
  engineering: HiOutlineWrenchScrewdriver,
  architecture: HiOutlineCpuChip,
  performance: HiOutlineBolt,
  design: HiOutlinePaintBrush,
  container: HiOutlineCube,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
